---
- name: Configure NTP on Home-Lab switches
  hosts: sites_home_lab:&device_roles_access
  gather_facts: no

  tasks:
    - name: Configure NTP servers
      cisco.ios.ios_config:
        lines:
          - ntp server 0.pool.ntp.org
          - ntp server 1.pool.ntp.org

    - name: Verify NTP
      cisco.ios.ios_command:
        commands:
          - show ntp status
          - show clock
      register: ntp_output

    - name: Show NTP status
      debug:
        var: ntp_output.stdout_lines
